### ISSUE TITLE
dev: debug "out of resources" error

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#11] opened 2023-08-23 07:18 UTC
- some tests fail because of an unknown error message

- it'd be nice to pinpoint where in kakarot the bug was triggered (e.g. identify in which line the codebase errors out)

**Comment by jobez** [comment] 2023-08-24 00:08
here's an expanded traceback of the first test that has this failure mode:

```
Error in the called contract (0x0169c08795fea182365eea042de0d41c8ae685b1030c8c941adc42ff13bf457a):

/Users/jmsb/Library/Caches/pypoetry/virtualenvs/kakarot-wte-U8dZ-py3.9/lib/python3.9/site-packages/starkware/cairo/common/hash.cairo:16:18: Error at pc=0:7:
    let result = hash_ptr.result;
                 ^*************^

Got an exception while executing a hint.

Cairo traceback (most recent call last):

/Users/jmsb/Library/Caches/pypoetry/virtualenvs/kakarot-wte-U8dZ-py3.9/lib/python3.9/site-packages/starkware/cairo/common/math.cairo:130:15
    let low = [range_check_ptr];
              ^***************^

Unknown location (pc=0:149)



Error in the called contract (0x0169c08795fea182365eea042de0d41c8ae685b1030c8c941adc42ff13bf457a):

Error at pc=0:31:

Got an exception while executing a hint.

Cairo traceback (most recent call last):

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/memory.cairo:200:58
            word_dict, chunk_index_i + 1, chunk_index_f, element + 16 - offset_in_chunk_i
                                                         ^**********^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/memory.cairo:169:42
            let (w) = dict_read{dict_ptr=word_dict}(chunk_index_i);
                                         ^*******^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/memory.cairo:81:46
        let (chunk_index, offset_in_chunk) = unsigned_div_rem(offset, 16);
                                             ^**************************^

Unknown location (pc=0:371)



Error in the called contract (0x0647e597c549ce84cb20aeb72687d47b95f7ace3ab3b18277ba7781212058a1b):

/Users/jmsb/Library/Caches/pypoetry/virtualenvs/kakarot-wte-U8dZ-py3.9/lib/python3.9/site-packages/starkware/cairo/common/uint256.cairo:74:5: Error at pc=0:507:
    alloc_locals;
    ^***********^

Could not reach the end of the program. RunResources has no remaining steps.

Cairo traceback (most recent call last):

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:463:24
        let temp_pow = internal_exp(a=a, b=b_minus_one);
                       ^******************************^

/Users/jmsb/exps/internet-computers/starknet/kakarot-rpc/lib/kakarot/src/kakarot/instructions/stop_and_arithmetic_operations.cairo:464:24
        let (res, _) = uint256_mul(a, temp_pow);
                       ^**********************^
```

**Comment by greged93** [comment] 2023-09-01 11:56
Can we close this? The issue is very vague about which test(s) are failing

**Closed** 2023-09-08 08:02 UTC
Labels: timebox-1day
